package message

// RoleType defines the role of a message in a conversation.
// This follows the standard LLM conversation format where messages
// have specific roles that define their purpose and behavior.
type RoleType string

const (
	// RoleSystem represents a system message that sets the behavior
	// and context for the assistant. System messages are typically
	// sent at the beginning of a conversation to define the assistant's
	// personality, capabilities, or constraints.
	RoleSystem RoleType = "system"

	// RoleUser represents a message from the user to the assistant.
	// User messages contain the actual input or questions that the
	// user wants the assistant to respond to.
	RoleUser RoleType = "user"

	// RoleAssistant represents a message from the assistant to the user.
	// Assistant messages contain the AI's response to user input.
	// These are typically generated by the LLM provider.
	RoleAssistant RoleType = "assistant"
)
